/**
 * This class is automatically generated by mig. DO NOT EDIT THIS FILE.
 * This class implements a Java interface to the 'AlertMsg'
 * message type.
 */

public class AlertMsg extends net.tinyos.message.Message {

    /** The default size of this message type in bytes. */
    public static final int DEFAULT_MESSAGE_SIZE = 4;

    /** The Active Message type associated with this message. */
    public static final int AM_TYPE = 22;

    /** Create a new AlertMsg of size 4. */
    public AlertMsg() {
        super(DEFAULT_MESSAGE_SIZE);
        amTypeSet(AM_TYPE);
    }

    /** Create a new AlertMsg of the given data_length. */
    public AlertMsg(int data_length) {
        super(data_length);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new AlertMsg with the given data_length
     * and base offset.
     */
    public AlertMsg(int data_length, int base_offset) {
        super(data_length, base_offset);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new AlertMsg using the given byte array
     * as backing store.
     */
    public AlertMsg(byte[] data) {
        super(data);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new AlertMsg using the given byte array
     * as backing store, with the given base offset.
     */
    public AlertMsg(byte[] data, int base_offset) {
        super(data, base_offset);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new AlertMsg using the given byte array
     * as backing store, with the given base offset and data length.
     */
    public AlertMsg(byte[] data, int base_offset, int data_length) {
        super(data, base_offset, data_length);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new AlertMsg embedded in the given message
     * at the given base offset.
     */
    public AlertMsg(net.tinyos.message.Message msg, int base_offset) {
        super(msg, base_offset, DEFAULT_MESSAGE_SIZE);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new AlertMsg embedded in the given message
     * at the given base offset and length.
     */
    public AlertMsg(net.tinyos.message.Message msg, int base_offset, int data_length) {
        super(msg, base_offset, data_length);
        amTypeSet(AM_TYPE);
    }

    /**
    /* Return a String representation of this message. Includes the
     * message type name and the non-indexed field values.
     */
    public String toString() {
      String s = "Message <AlertMsg> \n";
      try {
        s += "  [stolenId=0x"+Long.toHexString(get_stolenId())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      try {
        s += "  [voltageData=0x"+Long.toHexString(get_voltageData())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      return s;
    }

    // Message-type-specific access methods appear below.

    /////////////////////////////////////////////////////////
    // Accessor methods for field: stolenId
    //   Field type: int, unsigned
    //   Offset (bits): 0
    //   Size (bits): 16
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'stolenId' is signed (false).
     */
    public static boolean isSigned_stolenId() {
        return false;
    }

    /**
     * Return whether the field 'stolenId' is an array (false).
     */
    public static boolean isArray_stolenId() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'stolenId'
     */
    public static int offset_stolenId() {
        return (0 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'stolenId'
     */
    public static int offsetBits_stolenId() {
        return 0;
    }

    /**
     * Return the value (as a int) of the field 'stolenId'
     */
    public int get_stolenId() {
        return (int)getUIntBEElement(offsetBits_stolenId(), 16);
    }

    /**
     * Set the value of the field 'stolenId'
     */
    public void set_stolenId(int value) {
        setUIntBEElement(offsetBits_stolenId(), 16, value);
    }

    /**
     * Return the size, in bytes, of the field 'stolenId'
     */
    public static int size_stolenId() {
        return (16 / 8);
    }

    /**
     * Return the size, in bits, of the field 'stolenId'
     */
    public static int sizeBits_stolenId() {
        return 16;
    }

    /////////////////////////////////////////////////////////
    // Accessor methods for field: voltageData
    //   Field type: int, unsigned
    //   Offset (bits): 16
    //   Size (bits): 16
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'voltageData' is signed (false).
     */
    public static boolean isSigned_voltageData() {
        return false;
    }

    /**
     * Return whether the field 'voltageData' is an array (false).
     */
    public static boolean isArray_voltageData() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'voltageData'
     */
    public static int offset_voltageData() {
        return (16 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'voltageData'
     */
    public static int offsetBits_voltageData() {
        return 16;
    }

    /**
     * Return the value (as a int) of the field 'voltageData'
     */
    public int get_voltageData() {
        return (int)getUIntBEElement(offsetBits_voltageData(), 16);
    }

    /**
     * Set the value of the field 'voltageData'
     */
    public void set_voltageData(int value) {
        setUIntBEElement(offsetBits_voltageData(), 16, value);
    }

    /**
     * Return the size, in bytes, of the field 'voltageData'
     */
    public static int size_voltageData() {
        return (16 / 8);
    }

    /**
     * Return the size, in bits, of the field 'voltageData'
     */
    public static int sizeBits_voltageData() {
        return 16;
    }

}
