/**
 * This class is automatically generated by ncg. DO NOT EDIT THIS FILE.
 * This class includes values of some nesC constants from
 * ../Nodes/antitheft.h.
 */

public class Constants  {
    public static final byte DETECT_DARK = 1;
    public static final byte ALERT_SOUND = 2;
    public static final byte DIS_SETTINGS = 42;
    public static final byte ALERT_RADIO = 4;
    public static final byte ALERT_LEDS = 1;
    public static final short DEFAULT_CHECK_INTERVAL = 1000;
    public static final byte EVENT_ID = 1;
    public static final byte DEFAULT_DETECT = 1;
    public static final byte AM_THEFT = 99;
    public static final byte AM_SETTINGS = 54;
    public static final byte COL_ALERTS = 26;
    public static final byte AM_ALERT = 22;
    public static final byte DEFAULT_ALERT = 1;
    public static final byte ALERT_ROOT = 1;
    public static final byte DETECT_ACCEL = 2;
}
